def additoin(x, y):
    x = 10
    y = 20
    #b = 20
    try:
        print("Result of Addition: ", x + b)
    except Exception as e:
        print("something went wrong. Try again later.")
        print("save to file: ", e)
    else:
        print('the operation is successful')
additoin(10, 20)